"""initial migration

Revision ID: 45e1fa727b61
Revises: 
Create Date: 2025-02-06 10:27:28.705194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e1fa727b61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquilinos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inquilinos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inquilinos_dni'), ['dni'], unique=True)
        batch_op.create_index(batch_op.f('ix_inquilinos_email'), ['email'], unique=True)

    op.create_table('propietarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('propietarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_propietarios_email'), ['email'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('propiedades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('propietario_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['propietario_id'], ['propietarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('monto_mensual', sa.Float(), nullable=False),
    sa.Column('deposito', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('propiedad_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.ForeignKeyConstraint(['propiedad_id'], ['propiedades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.create_index('idx_contrato_fechas', ['fecha_inicio', 'fecha_fin'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_fecha_fin'), ['fecha_fin'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_fecha_inicio'), ['fecha_inicio'], unique=False)

    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.create_index('idx_factura_contrato', ['contrato_id', 'fecha_emision'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_fecha_emision'), ['fecha_emision'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_pagado'), ['pagado'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facturas_pagado'))
        batch_op.drop_index(batch_op.f('ix_facturas_fecha_emision'))
        batch_op.drop_index('idx_factura_contrato')

    op.drop_table('facturas')
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contratos_fecha_inicio'))
        batch_op.drop_index(batch_op.f('ix_contratos_fecha_fin'))
        batch_op.drop_index(batch_op.f('ix_contratos_activo'))
        batch_op.drop_index('idx_contrato_fechas')

    op.drop_table('contratos')
    op.drop_table('propiedades')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('propietarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_propietarios_email'))

    op.drop_table('propietarios')
    with op.batch_alter_table('inquilinos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inquilinos_email'))
        batch_op.drop_index(batch_op.f('ix_inquilinos_dni'))

    op.drop_table('inquilinos')
    # ### end Alembic commands ###
